# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-12 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplinas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=5)),
                ('turma', models.CharField(max_length=2)),
                ('descricao', models.CharField(max_length=100, null=True)),
            ],
            options={
                'ordering': ['codigo'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='disciplinas',
            unique_together=set([('codigo', 'turma')]),
        ),
    ]
