# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-13 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplinas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplinas',
            name='turma',
            field=models.CharField(max_length=10),
        ),
    ]
