# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-12 03:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submissao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_submissao', models.DateTimeField(auto_now_add=True)),
                ('qtd_testes_corretos', models.IntegerField()),
                ('detalhes', models.TextField()),
            ],
            options={
                'ordering': ['data_submissao'],
            },
        ),
        migrations.AddField(
            model_name='labs',
            name='qtd_testes',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submissao',
            name='lab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labs.Labs'),
        ),
    ]
