# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-12 03:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0003_submissao_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Submissao',
            new_name='Submissoes',
        ),
    ]
