# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-08 22:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0007_labs_diff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labs',
            old_name='argumentos',
            new_name='arg_diff',
        ),
        migrations.RenameField(
            model_name='labs',
            old_name='diff',
            new_name='arg_exec',
        ),
    ]
